### ISSUE TITLE
Load Failed Problem

### ISSUE THREAD

**Issue by hhddd6** [IvanChernyshov/NistChemPy#13]
Some Structures can't be loaded.
For example:
X = nist.Compound('C25085534')
With the error of :
ValueError: could not convert string to float: 'Monomer  42.0797'

**Comment by IvanChernyshov** [comment]
@hhddd6 thanks for the info! I'll update the package in 2-3 weeks.

**Comment by IvanChernyshov** [comment]
@hhddd6 please check the new release. The package was tested for all compounds provided in sitemaps and it should work fine.

Please note that new release have no backward compatibility with previous version, so you will probably need to change your code.

Feel free to open the issue if something goes wrong.
